// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

type MissingPet struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	LastSeen string `json:"last_seen"`
	OwnerID  int64  `json:"owner_id"`
}

type MissingPetPhoto struct {
	ID          int64  `json:"id"`
	PetID       int64  `json:"pet_id"`
	EncodedData string `json:"encoded_data"`
}

type PetOwner struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Hash    []byte `json:"hash"`
}
