// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

type MissingPet struct {
	ID       int64
	Name     string
	Type     string
	LastSeen string
}

type MissingPetOwnerRel struct {
	ID           int64
	MissingPetID int64
	PetOwnerID   int64
	Foreign      interface{}
}

type MissingPetPhoto struct {
	ID          int64
	PetID       int64
	EncodedData string
}

type PetOwner struct {
	ID      int64
	Name    string
	Phone   string
	Email   string
	Address string
	Hash    []byte
}
